from_latest_tag = true
ignore_merge_commits = true
disable_changelog = false
disable_bump_commit = false
tag_prefix = "v"
branch_whitelist = ["main", "release/*"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
  "npm version {{version}} --no-commit-hooks --no-git-tag-version",
]
post_bump_hooks = [
  "vsce publish --no-git-tag-version --no-update-package-json --pat $VSCE_PAT --skip-duplicate",
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
"""

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]
