name: "Check git conventions"

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check conventional commits
        uses: cocogitto/cocogitto-action@v3
        with:
          check-latest-tag-only: true
